# 文件黑白名单配置
# 默认使用黑名单且优先级高
Black_Suffix_list:
  active: true
  suffix_list:
    - jpg
    - jpeg
    - png
    - mp3
    - mp4
    - gif

White_Suffix_list:
  active: true
  suffix_list:
    - js
    - html
    - json

---

# 正则配置
# url识别模块
#url_regex_rules: https:\/\/[a-zA-Z0-9\/.?=%&:]*|http:\/\/[a-zA-Z0-9\/.?=%&:]*
Url_regex: \b(?:https?://|www\.)\S+\b

# html中的uri
Html_Uri_regex: src=[\'"](.*?)[\'"]|href=[\'"](.*?)[\'"]

# ip地址
Private_Ip_regex: ((127\.0\.0\.1)|(10(?:\.(?:2(?:5[0-5]|[0-4]\d)|1\d{2}|[1-9]\d|\d)){3})|(172\.((1[6-9])|(2\d)|(3[01]))(?:\.(?:2(?:5[0-5]|[0-4]\d)|1\d{2}|[1-9]\d|\d)){2})|(192\.168(?:\.(?:2(?:5[0-5]|[0-4]\d)|1\d{2}|[1-9]\d|\d)){2}))(?!\d)
Public_Ip_regex: (?<!\d|\.)(?:(?:2[0-4]\d|25[0-5]|[01]?\d{1,2})\.){3}(?:2[0-4]\d|25[0-5]|[01]?\d{1,2})(?!\d|\.)

# api路由
Api_Uri_regex: (?:\/[a-zA-Z-_0-9]+)+

# 敏感信息识别
Person_ID_regex: ([1-9]\d{5}[1|2]\d{3}([0][1-9]|1[012])(0[1-9]|[12]\d|3[01])\d{3}[0-9Xx])
Phone_Num_regex: (?:(?<=\D)|^)(1[3-9]\d{9})(?:(?=\D)|$)
OSS_AK_regex: .*[A|a]ccess[K|k]ey[I|i][D|d].*["'].*?["']|.*[A|a]ccess[K|k]ey[S|s]ecret.*["'].*?["']|.*[S|s]ecret.*["'].*?["']|.*SECRET.*["'].*?["']
Github_Access_Token_regex: ([a-zA-Z0-9_-]*:[a-zA-Z0-9_-]*@github\.com)
Email_regex: \b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b
Js_Comment_regex: // .*
Private_Key_regex: ([-]+BEGIN [^\s]+ PRIVATE KEY[-]*)
Crypto_regex: ([Ee]ncrypt\(|[Dd]ecrypt\()

---

# URL/API自动验活配置
auto_requests: False
domain: []
http_method: [GET,POST]
allow_redirects: True
headers: []
