# 规则参考的优秀项目
# https://github.com/kelvinBen/AppInfoScanner
# https://github.com/momosecurity/FindSomething
# https://github.com/gh0stkey/HaE
# https://github.com/moyuwa/wechat_appinfo_wxapkg

# 文件相关配置
File_Config:
  WX_Applet_Path: H:\WeChat Files\WeChat Files\Applet
  Sleep_Time: 10
  Applet_Packet_Save_Path: app_code
  Unveilr_Depth: 2
  Unveilr_Path: modle/unveilr
  Unveilr_Program_Name: unveilr@2.0.1-win-x64.exe
  Excel_Folder: output

  # 默认使用黑名单且优先级高
  Black_Suffix_list:
    active: true
    suffix_list:
      - jpg
      - jpeg
      - png
      - mp3
      - mp4
      - gif
      - bmp
      - webp
      - avi
      - mov
      - flv
      - wmv
      - mkv
  White_Suffix_list:
    active: false
    suffix_list:
      - js
      - html
      - json


# 正则配置
Regex_Config:
  App_Name_regex: '"navigationBarTitleText": "(.*)",'

  # 常见顶级域名匹配
  Domain_regex: (https?://)?(([a-zA-Z0-9-_]{1,61}[a-zA-Z0-9-_]\.)+(?:com|org|net|edu|gov|int|mil|biz|info|name|pro|xyz|top|club|cn)(?::[0-9]{1,5})?)
  # 顶级域名pro
  #Domain_regex: (https?://)?(([a-zA-Z0-9-_]{1,61}[a-zA-Z0-9-_]\.)+(?:com|org|net|edu|gov|int|mil|biz|info|name|pro|aero|coop|museum|asia|cat|jobs|mobi|tel|travel|xxx|[a-z]{2}|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cu|cv|cw|cx|cy|cz|de|dj|dk|dm|do|dz|ec|ee|eg|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|sk|sl|sm|sn|so|sr|ss|st|su|sv|sx|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|za|zm|zw)(?::[0-9]{1,5})?)

  # url识别模块
  Url_regex: (?:https?://|www\.)[a-zA-Z0-9\./=:?%\+&_-]+
  # uri路由
  Uri_regex: (?:[\"']((?:[\./]+)?(?:/[a-zA-Z-_0-9?%=&\+\./]+)+)[\"'])

  # ip地址
  Private_Ip_regex: ((127\.0\.0\.1)|(10(?:\.(?:2(?:5[0-5]|[0-4]\d)|1\d{2}|[1-9]\d|\d)){3})|(172\.((1[6-9])|(2\d)|(3[01]))(?:\.(?:2(?:5[0-5]|[0-4]\d)|1\d{2}|[1-9]\d|\d)){2})|(192\.168(?:\.(?:2(?:5[0-5]|[0-4]\d)|1\d{2}|[1-9]\d|\d)){2}))(?!\d)
  Ip_regex: (?<!\d|\.)(?:(?:2[0-4]\d|25[0-5]|[01]?\d{1,2})\.){3}(?:2[0-4]\d|25[0-5]|[01]?\d{1,2})(?!\d|\.)

  # 敏感信息识别
  Person_ID_regex: ([1-9]\d{5}[1|2]\d{3}([0][1-9]|1[012])(0[1-9]|[12]\d|3[01])\d{3}[0-9Xx])
  Phone_Num_regex: (?:(?<=\D)|^)(1[3-9]\d{9})(?:(?=\D)|$)
  Email_regex: ([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,})

  # 宁可错杀不可放过系列
  Account_regex: (?:账[号户]|[Aa]ccount).{,30}
  Passwd_regex: (?:密码|[Pp]assw(?:or)?d).{,30}
  Test_regex: (?:测试).{,30}
  # api/access/secret/my key/id/value/token 大杂烩 超赞！
  AK_regex: (?:[Aa][Pp][Ii]|[Aa][Cc]{2}[Ee][Ss]{2}|[Ss][Ee][Cc][Rr][Ee][Tt]|[Mm][Yy]).{,20}(?:[Kk][Ee][Yy]|[Ii][Dd]|[Vv][Aa][Ll][Uu][Ee]|[Tt][Oo][Kk][Ee][Nn]).{,30}
  Github_Access_Token_regex: ([a-zA-Z0-9_-]*:[a-zA-Z0-9_-]*@github\.com)
  Js_Comment_regex: // .*
  Private_Key_regex: ([-]+BEGIN [^\s]+ PRIVATE KEY[-]*)
  Jwt_regex: (['"](ey[A-Za-z0-9_-]{10,}\.[A-Za-z0-9._-]{10,}|ey[A-Za-z0-9_\/+-]{10,}\.[A-Za-z0-9._\/+-]{10,})['"])

  # 敏感函数
  Crypto_regex: ([Ee]ncrypt\(|[Dd]ecrypt\()
  #Crypto_regex: \W(Base64\.encode|Base64\.decode|btoa|atob|CryptoJS\.AES|CryptoJS\.DES|JSEncrypt|rsa|KJUR|$\.md5|md5|sha1|sha256|sha512)[\(\.]


# URL/API自动验活配置
Request_Config:
  # 自动验活开关
  request_active: False

  # 去除一些常用遇到的域名, 正则or字符串, 黑白名单只取其一，白名单优先级高
  hostname_filter_rule:
    allowed: []
    disallowed:
      - github.com
      - baidu.com
      - google.com
      - qq.com
  # 去除一些ip, 正则or字符串, 黑白名单只取其一，白名单优先级高
  ip_filter_rule:
    allowed: []
    disallowed:  # 默认不扫描内网ip
      - ((127\.0\.0\.1)|(10(?:\.(?:2(?:5[0-5]|[0-4]\d)|1\d{2}|[1-9]\d|\d)){3})|(172\.((1[6-9])|(2\d)|(3[01]))(?:\.(?:2(?:5[0-5]|[0-4]\d)|1\d{2}|[1-9]\d|\d)){2})|(192\.168(?:\.(?:2(?:5[0-5]|[0-4]\d)|1\d{2}|[1-9]\d|\d)){2}))(?!\d)

  # uri的过滤规则
  uri_filter_rule:
    allowed: []
    disallowed: # 默认去除带 del (删除) 字样的uri
      - del
  # url拼凑规则,
  scrabbled_rule: []

  # 请求的方式
  http_methods:
    - GET
    - POST
  headers:
    User-Agent: powered by vv4ke
    Connection: close
  cookies:
    test_cookie: test
  params:
#    test: test
  json:
    test_json: test
  # 允许自动跳转
  allow_redirects: false
  timeout: 10
  verify: false
  proxies:
    http: http://127.0.0.1:10809
#    https: https://127.0.0.1:8080


  # 非 200 页面尝试绕过
  bypass_config:


# 基本漏洞扫描
Vuln_Scan_Config:
  vulscan_active: false
